apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |-
    global:
    route:
      receiver: microsoft-teams
      group_by: ['alertname', 'severity']
      group_wait: 10s
      repeat_interval: 30m

    receivers:
    - name: microsoft-teams
      webhook_configs:
      - url: 'http://{{ template "msteams.name" . }}:{{ $.Values.msteams.service.port }}/alertmanger'
        send_resolved: true