apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  {{- if not $.Values.grafana.autoscaling.enabled }}
  replicas: {{ $.Values.grafana.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.grafana.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "grafana.labels" . | nindent 8 }}
        {{- with $.Values.grafana.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.grafana.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "grafana.serviceAccountName" . }}
      securityContext:
        {{- toYaml $.Values.grafana.podSecurityContext | nindent 8 }}
      containers:
        - env:
          - name: METHOD
            value: WATCH
          - name: LABEL
            value: grafana_dashboard
          - name: LABEL_VALUE
            value: "1"
          - name: FOLDER
            value: /tmp/dashboards
          - name: RESOURCE
            value: both
          - name: NAMESPACE
            value: ALL
          - name: REQ_USERNAME
            valueFrom:
              secretKeyRef:
                key: grafana-admin-user
                name: {{ include "grafana.fullname" . }}-secret
          - name: REQ_PASSWORD
            valueFrom:
              secretKeyRef:
                key: grafana-admin-password
                name: {{ include "grafana.fullname" . }}-secret
          - name: REQ_URL
            value: http://localhost:3000/api/admin/provisioning/dashboards/reload
          - name: REQ_METHOD
            value: POST
          image: quay.io/kiwigrid/k8s-sidecar:1.28.0
          imagePullPolicy: IfNotPresent
          name: grafana-sc-dashboard
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp/dashboards
            name: sc-dashboard-volume
        - env:
          - name: METHOD
            value: WATCH
          - name: LABEL
            value: grafana_datasource
          - name: LABEL_VALUE
            value: "1"
          - name: FOLDER
            value: /etc/grafana/provisioning/datasources
          - name: RESOURCE
            value: both
          - name: REQ_USERNAME
            valueFrom:
              secretKeyRef:
                key: grafana-admin-user
                name: {{ include "grafana.fullname" . }}-secret
          - name: REQ_PASSWORD
            valueFrom:
              secretKeyRef:
                key: grafana-admin-password
                name: {{ include "grafana.fullname" . }}-secret
          - name: REQ_URL
            value: http://localhost:3000/api/admin/provisioning/datasources/reload
          - name: REQ_METHOD
            value: POST
          image: quay.io/kiwigrid/k8s-sidecar:1.28.0
          imagePullPolicy: IfNotPresent
          name: grafana-sc-datasources
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources
            name: sc-datasources-volume
        - name: {{ $.Values.grafana.podName }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: grafana-admin-user
                  name: {{ include "grafana.fullname" . }}-secret
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: grafana-admin-password
                  name: {{ include "grafana.fullname" . }}-secret
            - name: GF_PATHS_DATA
              value: /var/lib/grafana/
            - name: GF_PATHS_LOGS
              value: /var/log/grafana
            - name: GF_PATHS_PLUGINS
              value: /var/lib/grafana/plugins
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          securityContext:
            {{- toYaml $.Values.grafana.securityContext | nindent 12 }}
          image: "{{ $.Values.grafana.image.repository }}:{{ $.Values.grafana.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: {{ $.Values.grafana.portName }}
              containerPort: {{ $.Values.grafana.podPort }}
              protocol: {{ $.Values.grafana.portProtocol }}
          livenessProbe:
            {{- toYaml $.Values.grafana.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $.Values.grafana.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml $.Values.grafana.resources | nindent 12 }}
          {{- with $.Values.grafana.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
            - mountPath: /etc/grafana/grafana.ini
              name: {{ include "grafana.fullname" . }}-config
              subPath: grafana.ini
            - mountPath: /etc/grafana/provisioning/dashboards/sc-dashboard-provider.yaml
              name: sc-dashboard-provider
              subPath: provider.yaml
          {{- end }}
      {{- with $.Values.grafana.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
        - configMap:
            defaultMode: 420
            name: {{ include "grafana.fullname" . }}-config
          name: {{ include "grafana.fullname" . }}-config
        - configMap:
            defaultMode: 420
            name: {{ include "grafana.fullname" . }}-dashboard-config
          name: sc-dashboard-provider
      {{- end }}