{{- if or $.Values.grafana.datasources.enabled $.Values.grafana.forceDeployDatasources }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
{{ include "grafana.labels" $ | indent 4 }}
data:
  datasource.yaml: |-
    apiVersion: 1
{{- if $.Values.grafana.deleteDatasources }}
    deleteDatasources:
{{ tpl (toYaml $.Values.grafana.deleteDatasources | indent 6) . }}
{{- end }}
{{- if $.Values.grafana.prune }}
    prune: {{ $.Values.grafana.prune }}
{{- end }}
    datasources:
{{- $scrapeInterval := $.Values.grafana.datasources.defaultDatasourceScrapeInterval | default "30s" }}
{{- if $.Values.grafana.datasources.defaultDatasourceEnabled }}
    - name: "{{ $.Values.grafana.datasources.name }}"
      type: prometheus
      uid: {{ $.Values.grafana.datasources.uid }}
      {{- if $.Values.grafana.datasources.url }}
      url: {{ $.Values.grafana.datasources.url }}
      {{- else }}
      url: http://{{ include "prometheus.fullname" . }}-svc.{{ .Release.Namespace }}.svc:{{ $.Values.prometheus.service.port }}
      {{- end }}
      access: proxy
      isDefault: {{ $.Values.grafana.datasources.isDefaultDatasource }}
      jsonData:
        httpMethod: {{ $.Values.grafana.datasources.httpMethod }}
        timeInterval: {{ $scrapeInterval }}
        {{- if $.Values.grafana.datasources.timeout }}
        timeout: {{ $.Values.grafana.datasources.timeout }}
        {{- end }}
{{- if $.Values.grafana.datasources.exemplarTraceIdDestinations }}
        exemplarTraceIdDestinations:
        - datasourceUid: {{ $.Values.grafana.datasources.exemplarTraceIdDestinations.datasourceUid }}
          name: {{ $.Values.grafana.datasources.exemplarTraceIdDestinations.traceIdLabelName }}
{{- end }}
{{- if $.Values.grafana.datasources.alertmanager.enabled }}
    - name: "{{ $.Values.grafana.datasources.alertmanager.name }}"
      type: alertmanager
      uid: {{ $.Values.grafana.datasources.alertmanager.uid }}
      {{- if $.Values.grafana.datasources.alertmanager.url }}
      url: {{ $.Values.grafana.datasources.alertmanager.url }}
      {{- else }}
      url: http://{{ include "alertmanager.fullname" . }}-svc.{{ .Release.Namespace }}.svc:{{ $.Values.alertmanager.service.port }}
      {{- end }}
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: {{ $.Values.grafana.datasources.alertmanager.handleGrafanaManagedAlerts }}
        implementation: {{ $.Values.grafana.datasources.alertmanager.implementation }}
{{- end }}
{{- end }}
{{- if $.Values.grafana.additionalDataSources }}
{{ tpl (toYaml $.Values.grafana.additionalDataSources | indent 4) . }}
{{- end }}
{{- end }}