apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://{{ include "prometheus.fullname" . }}-svc.{{ .Release.Namespace }}.svc:{{ $.Values.prometheus.service.port }}",
                "version": 1
            }
        ]
    }