apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  grafana-admin-user: {{ $.Values.grafana.secrets.username | b64enc | quote }}
  grafana-admin-password: {{ $.Values.grafana.secrets.password | b64enc | quote }}
