{{- if $.Values.grafana.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "grafana.fullname" . }}-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "grafana.fullname" . }}-deployment
  minReplicas: {{ $.Values.grafana.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.grafana.autoscaling.maxReplicas }}
  metrics:
    {{- if $.Values.grafana.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.grafana.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $.Values.grafana.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.grafana.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
