---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "msteams.name" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  connectors.yaml: |
    {{- with $.Values.msteams.connectors }}
    connectors:
{{ toYaml . | indent 6 }}
    {{- end}}
    connectors_with_custom_templates:
{{- range $index, $connectorWithCustomTemplate := $.Values.msteams.connectorsWithCustomTemplates }}
      - request_path: {{ $connectorWithCustomTemplate.request_path }}
        template_file: /etc/template/custom_card_{{ $index }}.tmpl
        webhook_url: {{ $connectorWithCustomTemplate.webhook_url }}
{{- if hasKey $connectorWithCustomTemplate "escape_underscores" }}
        escape_underscores: {{ $connectorWithCustomTemplate.escape_underscores }}
{{- end }}
{{- end }}
