---
apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ template "msteams.name" . }}-card-template
 namespace: {{ .Release.Namespace }}
binaryData:
  card.tmpl: |-
{{- if $.Values.msteams.customCardTemplate }}
{{ $.Values.msteams.customCardTemplate | b64enc | indent 4 }}
{{- else }}
{{ .Files.Get "card.tmpl" | b64enc | indent 4 }}
{{- end }}
{{- range $index, $customCardTemplate := $.Values.msteams.connectorsWithCustomTemplates }}
{{- if hasKey $customCardTemplate "template_file" }}
  custom_card_{{ $index }}.tmpl: |-
{{ $customCardTemplate.template_file | b64enc | indent 4 }}
{{- end }}
{{- end }}
