{{- if $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-state-metrics.fullname" . }}-prometheus-servicemonitor
  namespace: {{ template "kube-state-metrics.namespace" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | indent 4 }}
  {{- with $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.additionalLabels }}
    {{- tpl (toYaml . | nindent 4) $ }}
  {{- end }}
  {{- with $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $ }}
  {{- end }}
spec:
  jobLabel: {{ default "app.kubernetes.io/name" $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.jobLabel }}
  {{- with $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.targetLabels }}
  targetLabels:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  {{- with $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  {{- include "servicemonitor.scrapeLimits" $.Values.kubeStateMetrics.prometheus.monitor | indent 2 }}
  {{- if $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.namespaceSelector }}
  namespaceSelector:
    matchNames:
    {{- with $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.namespaceSelector }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
    {{- with $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.selectorOverride }}
      {{- toYaml . | nindent 6 }}
    {{- else }}
      {{- include "kube-state-metrics.selectorLabels" . | indent 6 }}
    {{- end }}
      self-monitor: "true"
  endpoints:
    - port: http
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.interval $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.interval }}
      interval: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.interval | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.interval }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.scrapeTimeout $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.scrapeTimeout }}
      scrapeTimeout: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.scrapeTimeout | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.scrapeTimeout }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.proxyUrl $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.proxyUrl }}
      proxyUrl: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.proxyUrl | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.proxyUrl }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.enableHttp2 $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.enableHttp2 }}
      enableHttp2: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.enableHttp2 | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.enableHttp2 }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.honorLabels $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.honorLabels }}
      honorLabels: true
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.metricRelabelings $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metricRelabelings }}
      metricRelabelings:
        {{- toYaml ($.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.metricRelabelings | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metricRelabelings) | nindent 8 }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.relabelings $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.relabelings }}
      relabelings:
        {{- toYaml ($.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.relabelings | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.relabelings) | nindent 8 }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.scheme $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.scheme }}
      scheme: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.scheme | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.scheme }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.tlsConfig $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.tlsConfig }}
      tlsConfig:
        {{- toYaml ($.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.tlsConfig | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.tlsConfig) | nindent 8 }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.bearerTokenFile $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.bearerTokenFile }}
      bearerTokenFile: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.bearerTokenFile | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.bearerTokenFile }}
    {{- end }}
    {{- with ($.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.http.bearerTokenSecret | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.bearerTokenSecret) }}
      bearerTokenSecret:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- if $.Values.kubeStateMetrics.selfMonitor.enabled }}
    - port: metrics
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.interval $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.interval }}
      interval: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.interval | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.interval }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.scrapeTimeout $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.scrapeTimeout }}
      scrapeTimeout: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.scrapeTimeout | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.scrapeTimeout }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.proxyUrl $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.proxyUrl }}
      proxyUrl: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.proxyUrl | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.proxyUrl }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.enableHttp2 $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.enableHttp2 }}
      enableHttp2: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.enableHttp2 | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.enableHttp2 }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.honorLabels $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.honorLabels }}
      honorLabels: true
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.metricRelabelings $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metricRelabelings }}
      metricRelabelings:
        {{- toYaml ($.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.metricRelabelings | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metricRelabelings) | nindent 8 }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.relabelings $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.relabelings }}
      relabelings:
        {{- toYaml ($.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.relabelings | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.relabelings) | nindent 8 }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.scheme $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.scheme }}
      scheme: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.scheme | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.scheme }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.tlsConfig $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.tlsConfig }}
      tlsConfig:
        {{- toYaml ($.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.tlsConfig | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.tlsConfig) | nindent 8 }}
    {{- end }}
    {{- if or $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.bearerTokenFile $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.bearerTokenFile }}
      bearerTokenFile: {{ $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.bearerTokenFile | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.bearerTokenFile }}
    {{- end }}
    {{- with ($.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.metrics.bearerTokenSecret | default $.Values.kubeStateMetrics.serviceMonitor.monitor.prometheus.bearerTokenSecret) }}
      bearerTokenSecret:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}