{{- if $.Values.kubeStateMetrics.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ $.Values.kubeStateMetrics.serviceAccount.automountServiceAccountToken }}
metadata:
  labels:
    {{- include "kube-state-metrics.labels" . | indent 4 }}
  name: {{ template "kube-state-metrics.serviceAccountName" . }}
  namespace: {{ template "kube-state-metrics.namespace" . }}
{{- if $.Values.kubeStateMetrics.serviceAccount.annotations }}
  annotations:
{{ toYaml $.Values.kubeStateMetrics.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- if or $.Values.kubeStateMetrics.serviceAccount.imagePullSecrets $.Values.kubeStateMetrics.global.imagePullSecrets }}
imagePullSecrets:
  {{- include "kube-state-metrics.imagePullSecrets" (dict "Values" $.Values.kubeStateMetrics "imagePullSecrets" $.Values.kubeStateMetrics.serviceAccount.imagePullSecrets) | indent 2 }}
{{- end }}
{{- end -}}
